export const PROGRESSBAR_DATA_FETCHING = 'PROGRESSBAR_DATA_FETCHING';
export const PROGRESSBAR_DATA_LOADED = 'PROGRESSBAR_DATA_LOADED';
export const PROGRESSBAR_ERROR = 'PROGRESSBAR_ERROR';

export const SET_SELECTED_PROGRESSBAR = 'SET_SELECTED_PROGRESSBAR';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';